### ISSUE TITLE
Replicate Issue

### ISSUE THREAD

**Issue by Digiw0lf** [cshomo11/b2aExtraLife#5]
On the latest edition of nodecg.
 `UNCAUGHT EXCEPTION! NodeCG will now exit.
Error: Must supply a namespace when instantiating a Replicant
    at Replicant (C:\Users\USERNAME\nodecg\lib\replicant\replicant.js:53:10)
    at declare (C:\Users\USERNAME\nodecg\lib\replicator.js:131:9)
    at findOrDeclare (C:\Users\USERNAME\nodecg\lib\replicator.js:220:9)
    at Socket.socket.on.e (C:\Users\USERNAME\nodecg\lib\replicator.js:36:23)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at C:\Users\USERNAME\nodecg\node_modules\socket.io\lib\socket.js:514:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
`
I have removed my username but I'm sure you get the idea

**Comment by cshomo11** [comment]
I haven't converted this bundle over to a Node 0.9 bundle yet. There are a few breaking changes with the latest update. I'll try to take a look and see what it will take to get it running on 0.9+.

**Comment by Digiw0lf** [comment]
Awesome, you be great to have this working for extra life 2017

**Comment by cshomo11** [comment]
Okay I pushed a new update that should run for NodeCG v0.9+. Pull in the changes and see how it works. You'll need to add your Participant ID where I specified in the Usage notes.

**Comment by cshomo11** [comment]
I'm closing this issue for now. If any other issues arise from the 0.9 update just open an new issue.
